export default {
  "total": 165,
  "list": [
    {
      "question_feed_id": null,
      "feed_id": 100097,
      "feed_type": "Q",
      "feed_title": "姓名 一零一 手机 13310011001 提问",
      "feed_text": "\t按照中央宣传部、公安部联合部署开展的“全民反诈在行动”集中宣传月活动有关要求，近日，国家反诈中心推出《2023版防范电信网络诈骗宣传手册》，详细梳理10类高发电信网络诈骗案件特点和诈骗手法，深入介绍7大反诈利器的主要功能和使用方法，进一步扩大反诈宣传覆盖面，切实提升广大群众识骗防骗意识和能力。\t随着信息社会快速发展，传统犯罪持续下降，以电信网络诈骗为代表的新型网络犯罪已成为当前的主要犯罪形态。不法分子或打着“兼职刷单”的幌子，或以“提供网贷”为诱饵，甚至冒充公检法工作人员，挖空心思诈骗钱财。稍不留神，就有可能落入陷阱，不少人深受其害。严厉打击电信网络诈骗不仅是维护公共利益的现实需要，也是建设法治社会的题中之义。\t近年来，我国始终对电信网络诈骗保持高压严打态势。2022年12月1日起，《中华人民共和国反电信网络诈骗法》正式实施，为更好打击治理电信网络新型违法犯罪提供了法律支撑。与此同时，公安部会同工信部、中国人民银行陆续推出国家反诈中心APP、96110预警劝阻专线、反诈名片等七大反诈利器，为打击电信网络诈骗提供技术支持。2022年，全国公安机关深入开展“云剑”“断卡”“断流”等专项行动，累计侦破案件46.4万起，推动电信网络诈骗发案连续17个月同比下降。各地区各部门密切配合，累计拦截诈骗电话21亿次、短信24.2亿条，有力维护了人民群众财产安全和合法权益。此次国家反诈中心推出《2023版防范电信网络诈骗宣传手册》，进一步为公众防范提供了“参考指南”。在此基础上，有必要进一步加强全民防诈的意识和能力，尽快补齐反电信网络诈骗的“拼图”，共同构筑拦截电信网络诈骗的“防火墙”。\t尽管骗子的招数咄咄逼人，但只要掌握一个基本原则，骗子也很难得逞——对来路不明的人保持警惕，拒绝其提出的一切形式个人转账要求。由此，不仅需要公众学法知法，不断增强个人的防范意识和防骗能力，而且需要各地各部门扩大宣传力度、提高宣传精度，针对易受骗群体开展有针对性的服务。\t全民反诈，不仅需要打击到位，而且需要治理靠前。当前，犯罪分子以获取公民个人信息为电信网络诈骗前提，再针对不同群体开展诈骗活动，电信网络诈骗由广撒网式的“盲骗”向精准化诈骗转型，被害人愈加容易轻信和上当，这也是很多人感到“防不胜防”的关键。构建起全民反诈的坚固防线，首先就要更加有效地保护好个人信息，这既是普通人应该做好的基本功课，也是维",
      "feed_media": null,
      "feed_like": 0,
      "feed_like_status": 0,
      "feed_comment": 0,
      "feed_favorite": 0,
      "feed_favorite_status": 0
    },
    {
      "question_feed_id": null,
      "feed_id": 100103,
      "feed_type": "A",
      "feed_title": "数据显示，美国华尔街今年裁员将超万人",
      "feed_text": "\t中国日报6月17日电 英国《金融时报》16日报道，美国华尔街大型银行今年裁员将超过1.1万人。美国花旗银行本周告诉投资者，截至今年二季度末将裁员5000人，集中在投资银行和交易部门。此前，高盛集团和摩根士丹利银行已裁员数千名员工。\t随着美联储持续加息，市场并购和交易活跃度降低。数据显示，今年迄今，全球投行业务收入减少约16%，降至437亿美元。高盛首席执行官戴维·所罗门本周说，高盛面临的机遇已缩",
      "feed_media": "",
      "feed_like": 1,
      "feed_like_status": 0,
      "feed_comment": 0,
      "feed_favorite": 0,
      "feed_favorite_status": 0
    },
    {
      "question_feed_id": null,
      "feed_id": 100411,
      "feed_type": "Q",
      "feed_title": "testsecsecsec",
      "feed_text": "testsec|expr 928272142 + 867872532 ",
      "feed_media": null,
      "feed_like": 0,
      "feed_like_status": 0,
      "feed_comment": 0,
      "feed_favorite": 0,
      "feed_favorite_status": 0
    },
    {
      "question_feed_id": null,
      "feed_id": 100157,
      "feed_type": "A",
      "feed_title": "没有封面高考只是一个短暂停留的驿站",
      "feed_text": "文章摘要考试是个点，人生是条线；分数总有高低，奋斗不能停息。有人考场得意，就会有人考场失意。我们自己身边，想必也有没有发挥好的考生，他们除了郁闷、失落之外，也有不少在为之后的前路发愁。对学校、家长乃至相关方面而言，多多关心他们有什么计划，有什么出路，有什么需要帮一把的地方，怎样帮他们也走上成长成才的“立交桥”，同样十分重要。",
      "feed_media": "",
      "feed_like": 0,
      "feed_like_status": 0,
      "feed_comment": 0,
      "feed_favorite": 0,
      "feed_favorite_status": 0
    },
    {
      "question_feed_id": null,
      "feed_id": 100148,
      "feed_type": "A",
      "feed_title": "插入图片插入图片插入图片",
      "feed_text": "我爱中国",
      "feed_media": "",
      "feed_like": 1,
      "feed_like_status": 0,
      "feed_comment": 0,
      "feed_favorite": 0,
      "feed_favorite_status": 0
    },
    {
      "question_feed_id": null,
      "feed_id": 100155,
      "feed_type": "A",
      "feed_title": "文章有封面一越20年，“千万工程”何以点亮千家万户",
      "feed_text": "如果许你一个愿去邂逅最美乡村，你会想到什么，又会想到哪里呢？来浙江广袤的乡间田野吧，在梦想照进现实的诗意美景中，在“千万工程”点亮“浙”里万千乡村的真实写照中，你会找到答案。",
      "feed_media": "https://cdn.ruzhi.com/feed/article/cover/20230627/100149_1687831154625",
      "feed_like": 1,
      "feed_like_status": 0,
      "feed_comment": 0,
      "feed_favorite": 0,
      "feed_favorite_status": 0
    },
    {
      "question_feed_id": null,
      "feed_id": 100080,
      "feed_type": "Q",
      "feed_title": "18810100098我发的提问在朋友圈能看到吗",
      "feed_text": "\t\t杭州2022年第19届亚运会（The 19th Asian Games Hangzhou 2022），简称“杭州2022年亚运会”，将在中国浙江杭州举行，原定于2022年9月10日至25日举办；2022年7月19日亚洲奥林匹克理事会宣布将于2023年9月23日至10月8日举办，赛事名称和标识保持不变。&nbsp;[52]&nbsp;&nbsp;[133-134]&nbsp;&nbsp;\t截至2020年12月，本届亚运会共设40个竞赛大项，包括31个奥运项目和9个非奥运项目&nbsp;[1]&nbsp;&nbsp;。同时，在保持40个大项目不变的前提下，增设电子竞技、霹雳舞两个竞赛项目&nbsp;[62]&nbsp;&nbsp;。\t杭州2022年亚运会以“中国新时代·杭州新亚运”为定位、“中国特色、浙江风采、杭州韵味、精彩纷呈”为目标，秉持“绿色、智能、节俭、文明”的办会理念，坚持“以杭州为主，浙江全省共享”的办赛原则。&nbsp;[2]&nbsp;\t2023年4月25日起，为期三天的杭州亚运会代表团团长大会在杭州举行，亚洲45个国家和地区的奥委会代表参会&nbsp;[170]&nbsp;&nbsp;。 6月15日，杭州亚运会倒计时100天，亚运会火种在杭州良渚古城遗址公园大莫角山成功采集&nbsp;[190]&nbsp;&nbsp;[194]&nbsp;&nbsp;。",
      "feed_media": null,
      "feed_like": 0,
      "feed_like_status": 0,
      "feed_comment": 0,
      "feed_favorite": 0,
      "feed_favorite_status": 0
    },
    {
      "question_feed_id": null,
      "feed_id": 100402,
      "feed_type": "Q",
      "feed_title": "imdummtgwyrjignktjgr",
      "feed_text": "testsec",
      "feed_media": null,
      "feed_like": 0,
      "feed_like_status": 0,
      "feed_comment": 0,
      "feed_favorite": 0,
      "feed_favorite_status": 0
    },
    {
      "question_feed_id": null,
      "feed_id": 100085,
      "feed_type": "V",
      "feed_title": "18810100098视频审核通过后能不能修改？",
      "feed_text": "18810100098视频",
      "feed_media": "https://cdn.ruzhi.com/feed/user/20230615/100098_1686828481686",
      "feed_like": 1,
      "feed_like_status": 0,
      "feed_comment": 0,
      "feed_favorite": 1,
      "feed_favorite_status": 0
    },
    {
      "question_feed_id": null,
      "feed_id": 100083,
      "feed_type": "Q",
      "feed_title": "18810100098提问审核通过后修改了",
      "feed_text": "188101000981881010009818810100098",
      "feed_media": "https://cdn.ruzhi.com/feed/article/20230615/100098_1686828135311",
      "feed_like": 1,
      "feed_like_status": 0,
      "feed_comment": 0,
      "feed_favorite": 0,
      "feed_favorite_status": 0
    }
  ],
  "pageNum": 1,
  "pageSize": 10
}
